#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

init_udev() {
	[ -d /lib/udev/devices ] && cp -af /lib/udev/devices/* /dev/
	[ -c /dev/console ] || mknod -m 0600 /dev/console c 5 1
	[ -c /dev/null ] || mknod -m 0666 /dev/null c 1 3
	/sbin/udevd --daemon --resolve-names=never
	/sbin/udevadm trigger
	/sbin/udevadm settle
}

init_device_fs() {
	if [ -x /sbin/udevd ]; then
		init_udev
	fi
}

boot_hook_add preinit_essential init_device_fs

